<a href="https://colab.research.google.com/github/Aarya-Musale/Data-Science/blob/main/DS_Numpy_Continue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Operations**

In [ ]:
# Create an array of 4X4 zeros

import numpy as np

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# create an array with constant value

np.full((4,4),12,dtype = float)
#np.full((4,4),0,dtype=bool)

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [ ]:
# Create a numpy array of 4X4 with diagonal elements as True and non-diagonal elements as False

np.identity(4)  #Square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#in python except 0 '' [] () None everything is True
np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [ ]:
# Create a numpy array of 4X4 with diagonal elements as False and non-diagonal elements as True
~np.identity(5,dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [ ]:
# Access diagonal elements of numpy array

s = np.identity(5)
s.diagonal()

array([1., 1., 1., 1., 1.])

**Numpy Slicing and Indexing**

In [ ]:
x = np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
print(x[0])  #using index we can access one row at a time
print(x[3])

[0 1 2 3]
[12 13 14 15]


In [ ]:
x[3][3]   #row with element index

#we can also do like this
print(x[3,3])

15


In [ ]:
print(x[1,0])
print(x[5,3])

4
23


In [ ]:
x[2,2]

np.int64(10)

In [ ]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [ ]:
# replace 15 by 50
x[3,3] = 50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#access multiple rows

x[:]  #[start_index:stop_index]

# When user does not give start and stop it gives you whole thing or whole matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [ ]:
#access last 3 rows
x[3:]  # +ve indexing
x[-3:]  # -ve indexing

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[::-3]

array([[20, 21, 22, 23],
       [ 8,  9, 10, 11]])

In [ ]:
x[::-2]

array([[20, 21, 22, 23],
       [12, 13, 14, 50],
       [ 4,  5,  6,  7]])

In [ ]:
# column operation

x[:,:]  #[row,column]

In [ ]:
x[-2:,-2:]

array([[18, 19],
       [22, 23]])

In [ ]:
x[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])